language: go
go: 1.6
sudo: required

before_install:
  - mkdir -p $HOME/gopath/src/sourcegraph.com/sourcegraph
  - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/sourcegraph.com/sourcegraph/srclib
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/sourcegraph.com/sourcegraph/srclib
  - export PATH=$PATH:$HOME/gopath/bin
  - export GOBIN=$HOME/gopath/bin
# Ruby
  - curl -L https://get.rvm.io | bash -s stable --ruby
  - rvm reload
  - rvm install 2.2.2
  - rvm use 2.2.2
  - gem update bundler
# JavaScript and TypeScript
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
# Java and Basic
  - sudo add-apt-repository -y ppa:openjdk-r/ppa
  - sudo add-apt-repository -y ppa:cwchien/gradle 
# Python
  - sudo add-apt-repository -y ppa:fkrull/deadsnakes
  - sudo apt-get update
# Java, Basic, JavaScript, TypeScript, and Python
  - sudo apt-get install -y openjdk-8-jdk gradle-2.13 nodejs python3.5
  - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
# TypeScript
  - npm install -g typescript

install:
  - make

script:
  - make test
# TODO: add csharp
  - srclib toolchain install go java javascript typescript basic python ruby css
