language: go
go: 1.6
sudo: false

before_install:
  - mkdir -p $HOME/gopath/src/sourcegraph.com/sourcegraph
  - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/sourcegraph.com/sourcegraph/srclib
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/sourcegraph.com/sourcegraph/srclib
  - export PATH=$PATH:$HOME/gopath/bin
  - export GOBIN=$HOME/gopath/bin

install:
  - make

script:
  # checking sourcegraph/srclib#281
  - srclib toolchain install go
  - go test -race -v $(go list ./... | grep -v /vendor/)
  
