language: go
go: 1.5
sudo: false

before_install:
  - mkdir -p $HOME/gopath/src/sourcegraph.com/sourcegraph
  - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/sourcegraph.com/sourcegraph/srclib
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/sourcegraph.com/sourcegraph/srclib
  - export PATH=$PATH:$HOME/gopath/bin
  - export GOBIN=$HOME/gopath/bin
  - go get github.com/tools/godep

install:
  - go get -d -v ./...
  # (alexsaveliev) the block below provides a workaround for https://github.com/tools/godep/issues/359
  # We'll use specific godep version (34)
  - $HOME/godep/godep restore ./...
  # TODO (alexsaveliev) Replace block above with the block below when 
  # https://github.com/tools/godep/issues/359 will be fixed
  #- godep restore ./...
  - go build -v ./...
  - go install ./cmd/srclib

script:
  - go test -race -v ./...
  
