site_name: srclib documentation
site_description: Documentation for srclib, a cross-language source code analysis package.

docs_dir: sources

repo_url: https://sourcegraph.com/sourcegraph/srclib/

dev_addr: '0.0.0.0:8000'

theme_dir: ./theme/

google_analytics: ['UA-40540747-5', 'srclib.org']

pages:

- ['gettingstarted.md', 'Getting started']

# Installation
- ['installation/editor-plugins.md', 'Installation', 'Editor Plugins']
- ['installation/src.md', 'Installation', 'src']

# src command
- ['src/overview.md', 'src command', 'Overview']
- ['src/data-model.md', 'src command', 'Data Model']
- ['src/make.md', 'src command', 'Make']
- ['src/srcfile.md', 'src command', 'Srcfile']
- ['src/toolchains.md', 'src command', 'Toolchains']
- ['src/faq.md', 'src command', 'FAQ']

# Language analysis
- ['language-analysis/overview.md', 'Language analysis', 'Overview']
- ['language-analysis/scanner-output.md', 'Language analysis', 'Scanner Output']
- ['language-analysis/grapher-output.md', 'Language analysis', 'Grapher Output']
- ['language-analysis/dependency-resolution-output.md', 'Language analysis', 'Dependency Resolution Output']
- ['language-analysis/formatter.md', 'Language analysis', 'Formatter Output']
- ['language-analysis/openquestions.md', 'Language analysis', 'Open Questions']
- ['language-analysis/faq.md', 'Language analysis', 'FAQ']

# API
- ['api/overview.md', 'API', 'Overview']

theme: yeti
