site_name: srclib documentation
site_description: Documentation for srclib, a cross-language source code analysis package.

docs_dir: sources

repo_url: https://sourcegraph.com/sourcegraph/srclib/

dev_addr: '0.0.0.0:8000'

theme_dir: ./theme/

google_analytics: ['UA-40540747-5', 'srclib.org']

pages:

- ['gettingstarted.md', 'Getting Started']

# Editor Plugins
- ['plugins/emacs.md', 'Editor Plugins', 'Emacs']
- ['plugins/sublimetext.md', 'Editor Plugins', 'Sublime Text']
- ['plugins/vim.md', 'Editor Plugins', 'Vim']
- ['plugins/atom.md', 'Editor Plugins', 'Atom']
- ['plugins/creatingaplugin.md', 'Editor Plugins', 'Creating a Plugin']

# Language Toolchains
- ['toolchains/python.md', 'Language Toolchains', 'Python']
- ['toolchains/go.md', 'Language Toolchains', 'Go']
- ['toolchains/ruby.md', 'Language Toolchains', 'Ruby']
- ['toolchains/javascript.md', 'Language Toolchains', 'Javascript']
- ['toolchains/java.md', 'Language Toolchains', 'Java']

# Building
- ['building/srcfile.md', 'Library Authors', 'Srcfile Customization']
- ['building/uploading.md', 'Library Authors', 'Uploading to Sourcegraph']

# API
- ['api/overview.md', 'API', 'Overview']
- ['api/data-model.md', 'API', 'Data Model']
- ['api/make.md', 'API', 'src make']
- ['api/describe.md', 'API', 'src describe']

# Creating a Toolchain
- ['creatingtoolchain/overview.md', 'Creating a Toolchain', 'Overview']
- ['creatingtoolchain/output.md', 'Creating a Toolchain', 'Output Overview']
- ['creatingtoolchain/scanner-output.md', 'Creating a Toolchain', 'Scanner Output']
- ['creatingtoolchain/grapher-output.md', 'Creating a Toolchain', 'Grapher Output']
- ['creatingtoolchain/dependency-resolution-output.md', 'Creating a Toolchain', 'Dependency Resolution Output']
- ['creatingtoolchain/formatter.md', 'Creating a Toolchain', 'Formatter API']
- ['creatingtoolchain/openquestions.md', 'Creating a Toolchain', 'Open Questions']

- ['faq.md', 'FAQ']
